# Optional Lab: Python, Numpy and Vectorization

In [1]:
import numpy as np
import time

In [6]:
a = np.zeros(4)
print(f"np.zeros(4): a = {a}, shape = {a.shape}, datatype = {a.dtype}")
a = np.zeros((4, ))
print(f"np.zeros(4, ): a = {a}, shape = {a.shape}, datatype = {a.dtype}")
a = np.random.random_sample(4)
print(f"np.random.random_sample(4): a = {a}, shape = {a.shape}, datatype = {a.dtype}")

np.zeros(4): a = [0. 0. 0. 0.], shape = (4,), datatype = float64
np.zeros(4, ): a = [0. 0. 0. 0.], shape = (4,), datatype = float64
np.random.random_sample(4): a = [0.48868403 0.10014898 0.80236988 0.20670412], shape = (4,), datatype = float64


### Operations on Vectors

In [11]:
a = np.arange(10)
print(a)
print("a[-1] = ", a[-1])
try:
    c = a[10]
except Exception as e:
    print('The error message you will see is:')
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[-1] =  9
The error message you will see is:
index 10 is out of bounds for axis 0 with size 10


### Slicing

In [17]:
a = np.arange(10)
print(a)
print("a[2:7:1] = ", a[2:7:1])
print("a[2:7:2] = ", a[2:7:2])
print("a[3:] = ", a[3:])
print("a[:] = ", a[:])

[0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:] =  [3 4 5 6 7 8 9]
a[:] =  [0 1 2 3 4 5 6 7 8 9]


In [22]:
def my_dot(a, b):
    x = 0
    for i in range(a.shape[0]):
        x = x + (a[i] * b [i])
    return x

a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
dot = my_dot(a, b)
print("The result from the function I created is", dot)

The result from the function I created is 24


### Operations on Matrices

In [34]:
a = np.arange(6).reshape(-1, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])